env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - RELEASE_BUILDS=dist/kubekutr_darwin_amd64/kubekutr dist/kubekutr_linux_amd64/kubekutr dist/kubekutr_windows_amd64//kubekutr.exe

builds:
  - binary: kubekutr
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"

archives:
  - format: tar.gz
    files:
      - config.sample.toml
      - README.md
      - LICENSE
      - templates/*