[[deployments]]
name = "app"
replicas = 3
[[deployments.labels]]
name="service: app"
[[deployments.labels]]
name="tier: frontend"
[[deployments.containers]]
name = "app"
image = "myapp:latest"
envSecret = "myapp"
portInt = 3000
portName = "app-port"
command = '["./myapp"]'
args = "['--config','--hello']"
[[deployments.containers.envVars]]
name="hello"
value="iamsecret"
[[deployments.containers.volumeMounts]]
name = "config-dir"
mountPath = "/etc/config"
subPath = "config.toml"
[[deployments.volumes]] # Only ConfigMap volume source supported for now
name = "config-dir"

[[services]]
name = "app"
type = "NodePort"
port = 7000
targetPort = 8000
[[services.labels]]
name="service: app"
[[services.selectors]]
name="tier: frontend"

[[ingresses]]
name = "app"
[[ingresses.annotations]]
name="alb.ingress.kubernetes.io/healthy-threshold-count: '2'"
[[ingresses.ingressPaths]]
path="/503"
service="app"
port="use-annotation"

[[statefulsets]]
name = "db"
serviceName = "db-headless"
[[statefulsets.labels]]
name="service: postgres"
[[statefulsets.labels]]
name="tier: db"
[[statefulsets.containers]]
name = "postgres"
image = "postgres:latest"
envSecret = "postgres"
portInt = 5432
portName = "db-port"
[[statefulsets.containers.envVars]]
name="POSTGRES_DB"
value="sample"
[[statefulsets.containers.volumeMounts]]
name = "db-dir"
mount = "/var/lib/postgres"
[[statefulsets.volumes]]
name = "db-dir"
