go clean
rm -f kubekutr
go build -o kubekutr -ldflags="-X 'main.buildVersion=11d92d8 (2020-04-28 14:30:44 +0530)' -X 'main.buildDate=2020-04-29 15:03:18'"
stuffbin -a stuff -in kubekutr -out kubekutr ./templates:/templates
stuffing complete. binary size is 12333.36 KB and stuffed zip size is 3.20 KB.
./kubekutr -c config.yml s
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    service: app
    tier: frontend
spec:
  ports:
  - port: 3000
    name: app-port
    targetPort: app-port
    protocol: TCP
  type: ClusterIP
  selector:
    service: app
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    service: app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      service: app
      tier: frontend
  template:
    metadata:
      labels:
        service: app
        tier: frontend
    spec:
      containers:
      - name: app
        image: myapp:latest
        command: ["./myapp"]
        args: ["--config", "--hello"]
        ports:
        - containerPort: 3000
          name: 
        resources:
          requests:
            memory: 750mi
            cpu: 400m
          limits:
            memory: 1500mi
            cpu: 800m
        readinessProbe:
          httpGet:
            path: hdbdhhduhdju
            port: app-port
            httpHeaders:
            - name: X-Kubernetes
              value: readinessProbe
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          timeoutSeconds: 7
        livenessProbe:
          httpGet:
            path: /api/liveness
            port: 3000
            httpHeaders:
            - name: X-Kubernetes
              value: livenessProbe
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 7
          failureThreshold: 5
        envFrom:
          - secretRef:
              name: myapp
        env:
        - name: hello
          value: iamsecret
        volumeMounts:
        - mountPath: /etc/config
          name: config-dir
          subPath: config.toml
      volumes:
        - name: config-dir
      nodeSelector:
        kubernetes.io/arch: arm
        kubernetes.io/os: linux---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    service: app
spec:
  ports:
  - port: 8000
    name: app-port
    targetPort: app-port
    nodePort: 30124
    protocol: UDP
  - port: 9000
    name: cache-port
    targetPort: 7000
    protocol: TCP
  type: NodePort
  selector:
    tier: frontend
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  annotations:
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
spec:
  rules:
    - http:
        paths:
          - path: /503
            backend:
              serviceName: app
              servicePort: use-annotation
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      service: postgres
      tier: db
  serviceName: db-headless
  template:
    metadata:
      labels:
        service: postgres
        tier: db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 3000
          name: db-port
        resources:
          requests:
            memory: 750mi
            cpu: 400m
          limits:
            memory: 1500mi
            cpu: 800m
        envFrom:
          - secretRef:
              name: postgres
        env:
        - name: POSTGRES_DB
          value: sample
        volumeMounts:
        - mountPath: /var/lib/postgres
          name: db-dir
      volumes:
        - name: db-dir
