name: kubekutr
version: git
summary: Cookie cutter templating tool for scaffolding K8s manifests.
description: |
  kubekutr lets you quickly scaffold a bespoke configuration for Kubernetes resource manifests with an opinionated GitOps
  directory structure.
confinement: devmode
base: core18

parts:
  kubekutr:
    plugin: go
    go-importpath: github.com/mr-karan/kubekutr
    source: .
    source-type: git
    override-build: |
      go get -u github.com/knadh/stuffbin/...
      go build -o kubekutr -ldflags="-X 'main.buildVersion=${VERSION}' -X 'main.buildDate=${BUILD_DATE}'"
      /root/go/bin/stuffbin -a stuff -in kubekutr -out kubekutr ./templates:/templates
      snapcraftctl build

apps:
  kubekutr:
    command: bin/kubekutr